name: fclone

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: fclone install
        run: |
          # 安装 fclone
          wget -qO- https://api.github.com/repos/mawaya/rclone/releases/latest \
          | grep browser_download_url | grep linux-amd64 | cut -d '"' -f 4 \
          | wget --no-verbose -i- -O- 
          ls
